import React, { forwardRef } from 'react';
import { Device } from '../types/device';
import dynamic from 'next/dynamic';

// Dynamically import the chart to avoid SSR issues with Recharts
const Chart = dynamic(() => import('./Chart'), { ssr: false });

interface ReportContainerProps {
  device: Device;
}

const ReportContainer = forwardRef<HTMLDivElement, ReportContainerProps>(
  ({ device }, ref) => {
    return (
      <div
        ref={ref}
        // Use exact hex codes to prevent html2canvas from crashing on lab() / oklch() colors generated by Tailwind v4
        className="absolute left-[-9999px] top-[-9999px] bg-[#ffffff] text-[#000000] p-10 flex flex-col items-center"
        style={{ width: '210mm', minHeight: '297mm' }}
      >
        <div className="w-full flex flex-col items-center border-b-2 border-[#e5e7eb] pb-6 mb-8">
          <h1 className="text-3xl font-bold text-[#1f2937]">Company Name Inc.</h1>
          <h2 className="text-xl text-[#4b5563] mt-2">Device Performance Report</h2>
          <p className="text-sm text-[#6b7280] mt-4" suppressHydrationWarning>
            Generated on: {new Date().toLocaleDateString()}
          </p>
        </div>

        <div className="w-full mb-8">
          <h3 className="text-2xl font-semibold mb-2">Device Details</h3>
          <div className="grid grid-cols-2 gap-4 text-lg">
            <div><strong>Name:</strong> {device.name}</div>
            <div><strong>ID:</strong> {device.id}</div>
            <div><strong>Status:</strong> {device.status}</div>
            <div><strong>Location:</strong> {device.location}</div>
          </div>
        </div>

        <div className="w-full flex flex-col items-center justify-center mb-12 flex-grow">
          <h3 className="text-2xl font-semibold mb-6">Performance Trend</h3>
          {/* Centered Chart Wrapper */}
          <div className="w-full flex justify-center">
            <Chart data={device.metrics} />
          </div>
        </div>

        <div className="w-full">
          <h3 className="text-2xl font-semibold mb-4">Summary Table</h3>
          <table className="w-full text-left border-collapse border border-[#e5e7eb]">
            <thead>
              <tr className="bg-[#f3f4f6]">
                <th className="border border-[#e5e7eb] p-2">Month</th>
                <th className="border border-[#e5e7eb] p-2">CPU Usage (%)</th>
                <th className="border border-[#e5e7eb] p-2">Memory Usage (%)</th>
                <th className="border border-[#e5e7eb] p-2">Bandwidth (Mbps)</th>
              </tr>
            </thead>
            <tbody>
              {device.metrics.map((metric) => (
                <tr key={metric.month}>
                  <td className="border border-[#e5e7eb] p-2">{metric.month}</td>
                  <td className="border border-[#e5e7eb] p-2">{metric.cpuUsage}</td>
                  <td className="border border-[#e5e7eb] p-2">{metric.memoryUsage}</td>
                  <td className="border border-[#e5e7eb] p-2">{metric.bandwidth}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    );
  }
);

ReportContainer.displayName = 'ReportContainer';

export default ReportContainer;
